version: "3"

services:
    app:
        build: .
        ports:
          - "4001:4001"
        restart: unless-stopped
        environment:
          - FLASK_RUN_PORT: 4001
          - MONGODB_CONNSTRING: 'mongodb://flmc:fdbpwd1@mongo:27017/'
          - TZ: 'Asia/Shanghai'
        
    mongo:
        image: mongo:focal
        restart: unless-stopped
        environment:
          - MONGO_INITDB_ROOT_USERNAME: flmc
          - MONGO_INITDB_ROOT_PASSWORD: fdbpwd1