version: "3"


services:
    app:
        build: .
        ports:
          - "4001:4001"
        restart: unless-stopped
        volumes:
          - "/cert:/cert"
        environment:
          FLASK_RUN_PORT: 4001
          MONGODB_CONNSTRING: 'mongodb://user:pwd@mongo:27017/'
          TZ: 'Asia/Shanghai'
        
    mongo:
        image: mongo:focal
        restart: unless-stopped
        volumes:
          - "/home/*/mdb:/data/db"
        environment:
          MONGO_INITDB_ROOT_USERNAME: ###
          MONGO_INITDB_ROOT_PASSWORD: ###